version: "3.3"
services:
  xteve: # Should be exact same name as "id" field in config.json
    container_name: xteve  # Should be exact same name as "id" field in config.json
    image: dnsforge/xteve:latest # Try to avoid "latest" tag. As it may break configs in the future.
    environment:
      - TZ=${TZ} # Can use any env variable. List in runtipi/templates/env-sample
    volumes:
      - ${APP_DATA_DIR}/data/xteve:/home/xteve/conf # Always start the path with ${APP_DATA_DIR}. This will put all data inside app-data/my-app/data
    ports:
      - ${APP_PORT}:8173
    restart: unless-stopped
    networks:
      - tipi_main_network