version: '3.7'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    ports:
      - ${APP_PORT}:80
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_FOLDER_HOST}/app-data:/srv/app-data
      - ${ROOT_FOLDER_HOST}/media:/srv/media
      - ${APP_DATA_DIR}/data/db:/database
      - ${APP_DATA_DIR}/data/config:/config
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.filebrowser.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.filebrowser.entrypoints: websecure
      traefik.http.routers.filebrowser.service: filebrowser
      traefik.http.routers.filebrowser.tls.certresolver: myresolver
      traefik.http.services.filebrowser.loadbalancer.server.port: 80
